### ISSUE TITLE
Packet Dumps

### ISSUE THREAD

**Issue by taylorjdlee** [Knightro63/phomemo#2]
Hi @Knightro63 I'm working on a linux driver repo for phomemo printers here https://github.com/vivier/phomemo-tools if you could provide packet dumps for the P12Pro, D35, D30 and M220 that would be great. We've currently got the M02, M02s, M110 and M120 confirmed to work on our end.

**Comment by Knightro63** [comment]
Hi @taylorjdlee, I am sorry but I no longer have those printers.
