### ISSUE TITLE
M832

### ISSUE THREAD

**Issue by Blackheart8788** [Knightro63/phomemo#4]
Good afternoon,

Can model M832 be enabled for this package and at what time?

**Comment by Knightro63** [comment]
Hi @Blackheart8788,

Have you tried using this model of printer with this package. It might work without any updates. 

If you have the printer I would try using the example to see if it works. All of the current printers I used uses the same protocol for communication. Just change the size of the paper to the size of the printer paper you put in. In this case it is adjustable so it is even easier.

For the example you will need to change a couple of things to get it to work. Change the the type of printer to 'M220',  and the size of the label to something small so you can use the same paper over and over for testing. You will also need to add the name of the printer you are looking for in the initstate function like below.
```dart
    bluetooth = Bluetooth(
      onUpdate: _bleUpdate,
      names: ['M832','Q______________'] //'Q______________' Place the name of the printer here.
    );
```

the last thing that might need to change is the rotate variable for printLabel, but I don't think this will be an issue if you use the m220 print format. I am also unsure if the printer has a name like the m220 or if the name is M832. It will probable say on the box, the instructions, or somewhere else.

If you cant find the name easily download Nordic's nrf Connect app to see what name comes up.

If it works I will add it to the list of working printers.

Let me know if this helps.

**Comment by Blackheart8788** [comment]
Good afternoon, 

I applied your recommendations, but unfortunately for me, I didn't get it to work

I'll close this issue because it is something related to the printer and not your package.
